# Generated by Django 6.0 on 2025-12-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(default='Other', max_length=100, verbose_name='Type of Food'),
            preserve_default=False,
        ),
    ]
