# Generated by Django 5.2.6 on 2026-01-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_restaurantlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='happy_hour',
            field=models.TextField(blank=True, help_text='Happy hour details (days, times, specials)', null=True),
        ),
    ]
