# Generated by Django 6.0 on 2026-01-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_customlist_customlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlist',
            name='list_type',
            field=models.CharField(choices=[('dish', 'Dishes'), ('restaurant', 'Restaurants')], max_length=20),
        ),
    ]
