# Generated by Django 6.0 on 2026-01-15 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postcomment_postlike'),
        ('restaurants', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('menu_item_added', 'New menu item at favorite restaurant'), ('review_like', 'Someone liked your review'), ('comment', 'Someone commented on your review'), ('follow', 'Someone followed you'), ('post_like', 'Someone liked your post'), ('post_comment', 'Someone commented on your post')], max_length=50),
        ),
    ]
