# Generated by Django 6.0 on 2026-01-13 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_post_type_alter_post_menu_item_and_more'),
        ('restaurants', '0014_alter_customlist_list_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='custom_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.customlist'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('review', 'Review'), ('diary', 'Diary Entry'), ('list', 'List')], default='review', max_length=10),
        ),
    ]
